package com.example.latte.model;  // Ensure this matches your package path

import androidx.room.Entity;
import androidx.room.PrimaryKey;
import androidx.room.ColumnInfo;

@Entity(tableName = "tasks")  // Room Entity for the tasks table
public class TaskModel {

    @PrimaryKey(autoGenerate = true)
    private int id;  // Primary key for each task (Auto-generated by Room)

    @ColumnInfo(name = "title")
    private String title;  // Title of the task

    @ColumnInfo(name = "description")
    private String description;  // Description of the task

    @ColumnInfo(name = "due_date")
    private String dueDate;  // Due date for the task

    @ColumnInfo(name = "priority")
    private int priority;  // Priority of the task (1 = High, 2 = Medium, 3 = Low)

    @ColumnInfo(name = "is_completed")
    private boolean isCompleted;  // Whether the task is completed or not

    @ColumnInfo(name = "new_column")  // The new column added in the migration
    private int newColumn;  // Default value will be 0 for this column

    // Default constructor (required by Room)
    public TaskModel() {
    }

    // Constructor with parameters, now including the new column
    public TaskModel(String title, String description, String dueDate, int priority, boolean isCompleted, int newColumn) {
        this.title = title;
        this.description = description;
        this.dueDate = dueDate;
        this.priority = priority;
        this.isCompleted = isCompleted;
        this.newColumn = newColumn;  // Initialize the new column value
    }

    // Getters and Setters for each field
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDueDate() {
        return dueDate;
    }

    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    public int getPriority() {
        return priority;
    }

    public void setPriority(int priority) {
        this.priority = priority;
    }

    public boolean isCompleted() {
        return isCompleted;
    }

    public void setCompleted(boolean completed) {
        isCompleted = completed;
    }

    // Getter and Setter for the new column
    public int getNewColumn() {
        return newColumn;
    }

    public void setNewColumn(int newColumn) {
        this.newColumn = newColumn;
    }

    // Optional: Override toString() for debugging and display purposes
    @Override
    public String toString() {
        return "TaskModel{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", dueDate='" + dueDate + '\'' +
                ", priority=" + priority +
                ", isCompleted=" + isCompleted +
                ", newColumn=" + newColumn +  // Include the new column in toString
                '}';
    }
}
